token:
  expiration_time: 864000000 
  secret: '{cipher}AYCB5DjUB0dcjRL1IzfwX8jw6fNqLFKs4TCfqNebSld7vapcpsGyMGv8ItZbIN/5mgFY+z1dxQnOn205bP9ZVx1ODkbrQhcePvPPMPKIrF8jlrWXs9TxTO2poobpGTrReNVMwoUkmedgLYu47+L0A3a+LaAZL7mHvJ/rNMZ3WWNaj0JoluIiTqh/4YfEx8Efc0LqPVxTzdLhjTMuwUlkNphBi71/RUJ7Zhlp9J8pX0A86gP/ir5LV4PthIViBYVqj73SKcJwoZMdNVxlaI5TZQdLA5VMCIzsoloyLrUaMZs0OCPRWQBBx3J2WtY/Y2EiRYoMQKnlCfZG5+sI+o2x4Rt3vvckxAFBWpFyG7bIbG3CjDgdpGWERKbeJwkWv7AjkcWbFCzK+bfsA9ZmkNQEh5T6Jx9VD0RaK0kHcfTIkMAXjEdvi1sUwamShHR3LualDj9lBZu1/+8lO0fOWArNrBOXB23IU1x1RO0g3UvwfuF43ONddBx0hEIf6NvUuJrwCkTV6uloU59lEH+i4QheU/ETbW2ZneZBjYaqf03nmb7vpbOE0+p1ipfpzh0Vvckw/Lpk8C3B2hANtob6i8hnXRdfsGdDx/HQ1NqfDBrTmSL7Hgv1lwPIXMqtFiPluukbPJ4='

gateway:
  ip: 172.18.0.1
