token:
  expiration_time: 864000000 
  secret: '{cipher}AYAVlHZOzs7bTx16agkAga4h/dROozD9ndag0Wqf/k6DTie1Mt/+bDTH7/s7wRtmhZLpPyAdmUFDLNfSuScNmCcaSCsp6eKIgM+F/PoU8GG2IBhOzJpYkW7B0zt7dAdI+2sEe9Dz5g8RgyXo7vhixl2ZBcPLivKAVjrP7CGjxS4ix/hK6WzVmVSacaPm3zCEXAzW2jzgi3qKVafMH1jsVafJ/SJvcMI8O8jp0nLEkqTqvyxyBMVd1AH1V6OkZCqb9KhZK4Tt/g9fo8jftaWdtRVJmdosd/DWHhoo886na58fxwzR5Ke86C7P7VWdXKy9QfGJt4ZQNdhMaHqs8VMx9e9kADpNCxaqPurIdoBmr0zxRN+JGct3rHuvKHYhsfWmDSZE2nc3Q/dQ0j3lnOpf+jLaWxKUOkjzFY5qxz2sGdsR4CHUsn1DdeOQ5jCxA1Xtix2/9JdP+Lz85d/f3tYRcqMtxIW5pMHXsvnCfNcyc9EvR84haBWwcFBJ2tvvjfL3INzc9jYe4Sr7Et5b7rWxQmd++YMUn9/Yz7Zd81JlZO8U8LcoqPxXL1AnwOmZmuTLhiyO9gmSMBi1WmSUPiKIxKb+oPjsKsTIIh+Z2KRbEIU+pA=='

gateway:
  ip: 172.18.0.1
